### ISSUE TITLE
An mqtt server with no username/password is not possible.

### ISSUE THREAD

**Issue by shevett** [tom-23/TasmoManager#1]
The form requires you to fill out all the fields.

**Comment by tom-23** [comment]
@shevett I've just pushed new changes that fix this. In addition, I've reworked the MQTT Servers tab to be more user friendly. I've released it as another alpha: https://github.com/tom-23/TasmoManager/releases/tag/v1.0.0-alpha.2. Appveyor is currently building macOS binaries so they'll pop up in like 5 mins. Let me know if it solves the issue!

**Comment by tom-23** [comment]
This should be fixed. Thanks for reporting!
