### ISSUE TITLE
A customisable table, with more fields such as FriendlyName

### ISSUE THREAD

**Issue by chriscn** [tom-23/TasmoManager#2]
Hi Tom,
I just wanted to start out by saying how much I do love this project. Looks absolutely wonderful on my Mac and if you ever need any help with testing do get in contact. 

My slight feature request would be the ability to add and remove fields from the main table. It would be great in regards to finding which device for instance in my house each plug (we have around 12) gets a unique identifier e.g. 120-01 depending on which floor and then which room etc. So it would be great if I could have the Friendly Name in the actual table list rather than just on the side.

Best,
Christopher

**Comment by tom-23** [comment]
Hi Christopher!

I've implemented your suggestions and have added a "friendly name" and "Module" column. You can change the visibility by clicking the "View" menu on the menu bar and checking/unchecking the desired options. (NOTE: These settings are persistent so it'll remember what you last had visible when you restart the app.) These changes should appear in the next alpha (v1.0.0-alpha.8). You can update in the app by clicking Settings > Software Update and switching to the alpha channel.

Thanks for saying you love the project!

Kind Regards,
Tom

**Comment by tom-23** [comment]
Implemented!
