### ISSUE TITLE
A beginner friendly desktop UI ...

### ISSUE THREAD

**Issue by Pewibe** [tom-23/TasmoManager#4]
Hi Tom
This might be not an usual issue but in absence of a discussion / help column I use this instrument. Your headline of the project is "A beginner friendly desktop UI for Tasmota flashed devices". As an ordinary beginner I tried to follow you and install the TM to get experienced. After one minute I gave up because of the following unanswered questions:
1. Which OS platforms are supported? Any chance for a windows10 user?
2. Do I have to compile / make a binary like a developer? 
3. Did I oversee a installable binary? Or in general: How is TM installed?
4. 4. Anything necessary to run the installed app?
Hope this basic stuff doesn't bother you too much. But maybe more practical users give you a kick for additional coding - your favour. Documentation is not the nicest job, but sometimes necessary. Thanks for your work and your answer.

**Comment by tom-23** [comment]
In answer to your questions,

1. Windows 10 is supported (8.1 and 7 should be too) and so is macOS
2. Nope, installers/binaries can be found [here](https://github.com/tom-23/TasmoManager/releases)
3. Yes, there is an installer for both Windows and macOS
4. Nope, the installer installs everything and adds a start menu item

In summary, you're right. I need to get some more docs written. About 2 weeks ago I wrote a [Getting Started](https://github.com/tom-23/TasmoManager/wiki/Getting-Started) page on the wiki section but I could probably do with adding a link to it on the README.md file.

**Comment by Pewibe** [comment]
Tom, let me dig a little bit deeper, because your 4 answers lead to success to get the app run. The last sentence in your one-page-wiki "Tasmota devices should then begin to appear in the list" was not my event - TM shows not any one of my devices. Any hint for me if you look to the next 3 screens showing the menu activation "Devices / Add unconfigured device..."?
![Clipboard01](https://user-images.githubusercontent.com/42893315/114229568-4e142380-9978-11eb-9ebb-41e28b6f66a7.jpg)
![Clipboard02](https://user-images.githubusercontent.com/42893315/114229576-51a7aa80-9978-11eb-8bca-88c00059b817.jpg)
![Clipboard03](https://user-images.githubusercontent.com/42893315/114229595-540a0480-9978-11eb-89d0-c7154ac026e7.jpg)

**Comment by tom-23** [comment]
Could you tell me a bit more information about your setup like what MQTT server you are running and what version of tasmota you have installed? Also, for discovery to work, you must have `SetOption19` set to `0` on the devices.

**Comment by Pewibe** [comment]
1. I checked 3 of 16 active devices for SO19=0 --> OK.
2. I checked 8 of 16 active devices for Tasmota version: differs from 8.3.1 to 9.1.0 to 9.3.1.
3. MQTT Server is Eclipse Mosquitto MQTT brokerr (64 bit) Version 1.6.10 running on Windows Server 2012R2. Default port 1883 is used with no user/password.
4. TM shows in upper right corner the Server, port and status "connected".

**Comment by tom-23** [comment]
Okay then, it could be two things:
1. The tasmota/discovery topic got deleted resulting in no devices being detected.
2. There are access control rules present on the server preventing TasmoManager from reading/writing topics.

Could you connect to the server using TasmoManager and restart a tasmota device? (using the WebUI or physically) If the device shows up, you just need to give all devices on the server a restart and they should all begin to be discovered again.

Does your server need to be authenticated to read/write topics? (do your tasmota devices use a username or password to authenticate with mosquitto?) If so, you will need to authenticate with a user which can read and write to the server in order to use TasmoManager.

This seems really strange.

Thanks!
Tom

**Comment by Pewibe** [comment]
Your item 2: As I wrote one message above, I do not use login at MQTT server (no user, no password).

Your item 1: I restartet a test device several times but didn't discover any topic related to tasmota/discovery. I do not know how it should look, but there is nothing. Other states of the device are to be seen which means that the MQTT publication works. Btw, I can see an MQTT topic "TasmoManager_v1" and 3 sublevels until "TasmoManager_v1.0.0-alpha.10.alive" with value FALSE. So my question: Which topic of my test device I have to discover that the discovery mechanism works?

**Comment by tom-23** [comment]
So for device discovery to work, the topic `tasmota/discovery` needs to be present in the root of the MQTT server. Like this:

<img width="215" alt="Screenshot 2021-04-10 at 3 27 34 pm" src="https://user-images.githubusercontent.com/24756018/114273271-540a1300-9a11-11eb-903f-9b2521763c51.png">

It could be that you're running tasmota-lite.bin on your devices which DO NOT include the discovery feature. What MQTT client are you using btw? I can't seem to find the TasmoManager_v1  topics?

Cheers, Tom

**Comment by Pewibe** [comment]
First of all, I'm always loading module tasmota-DE.bin. Other versions (mini) are used only interim for update.

As MQTT system I have installed 2 different which I can use alternativ: a) Mosquitto with ...sub and ...pub b) Iobroker with so called Sonoff adapter. The case b) has an included object browser to see all topics like your example.

After these lines you see a screenshot of one of my devices and the TasmoManager topic. Your needed topic tasmota/discovery is missing overall. Beside our chat to get TM running you maybe should consider this situation as improvement for TM: If 'refresh device list' is activated, first the presence of the correct dicovery topics should be tested and the user should receive a detailed message what is missing. Now my screen:
![Clipboard00](https://user-images.githubusercontent.com/42893315/114281964-9d725680-9a41-11eb-8c3b-7e8334761100.jpg)

**Comment by tom-23** [comment]
Firstly, you can't use sonoff adapter (as I found out in Issue #3) because it doesn't allow you to read topics rather annoyingly. However, mosquito *should* be fine. If you want to use iobroker, you could use the mosquitto server and install mqtt adapter as a client. (I'm not a iobroker user myself so there could be a better way of doing things)

And yeah, you're right it would be a great improvement and not that difficult to implement plus some more error handling, in general, can make the user experience a bit better.

**Comment by tom-23** [comment]
If you're having issues with TasmoManager using Moqsuitto, could you download MQTTExplorer and check to see if the `tasmota/discovery` topic is present with a tasmota device connected?

**Comment by Pewibe** [comment]
Tom
I think you can close this thread. Your help lead to success (no use of sonoff adapter in iobroker). Beside iobroker-adapter mqtt-client there is an adapter mqtt broker/client. Which one you ment with 'install mqtt adapter'?

Your TM app is nice to handle and has a nice clear look. With the first usage there are a few items which I like to hand over to you as wish list for future improvement:
1. Already mentioned presence test of topic tasmota/discovery. If additionally unuseable MQTT brokers like iobroker/sonoff could be detected would be great!
2. During start of TM the former window size/position should be established again (configurable if you like).
3. During start of TM the former connected MQTT broker should be connected again (configurable if you like). 
4. The columns of the device list should be sorted by clicking the head. Today it looks like mess in my list.
5. A column 'Power' to display the relay status would be fine.
6. In sidebar I'm missing sensor/measurement results. 
7. For debugging of rules a status view of the Gpios, Leds (and more advanced of Vars, Mems, RuleTimers) would be a great feature if you have done most wanted features. I assume your fun in programming is not lost ;-)

Thanks again for your work,

**Comment by tom-23** [comment]
You can install an MQTT adapter for IOBroker but I'm not too sure on how it works. Anyways, thanks for the feature requests! I'll add those to the timeline when I get a chance :). Btw, I've created a docs site https://tom-23.github.io/tasmomanager-docs/ since you mentioned documentation 😁.
