### ISSUE TITLE
Sortable columns

### ISSUE THREAD

**Issue by schrej-zz** [tom-23/TasmoManager#9]
Hi,
as issue #4  was already closed, despite having some suggestions for enhancements, I like to bring up at least this request back as a separate issue (Enhancement):

The columns of the device list should be sorted by clicking the head. 

Thanks Joerg

**Comment by tom-23** [comment]
Implemented! It should make an appearance in the next release of TasmoManager. Thanks for submitting an issue!

**Comment by tom-23** [comment]
Feature present in [v1.0.0-alpha.13](https://github.com/tom-23/TasmoManager/releases/tag/v1.0.0-alpha.13).
